name: Supreme Cloud APK Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install Cloud Build Tools
        run: |
          pip install buildozer cython kivy
          sudo apt update
          sudo apt install -y git zip unzip autoconf autotools-dev libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
      - name: Build APK for OPPO A78
        run: |
          buildozer init
          sed -i 's/package.name = myapp/package.name = supremesia/' buildozer.spec
          sed -i 's/package.domain = org.test/package.domain = org.sohailmaster/' buildozer.spec
          sed -i 's/android.archs = armeabi-v7a/android.archs = arm64-v8a/' buildozer.spec
          buildozer android debug
      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: SIA-Supreme-Weapon
          path: bin/*.apk
